services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dboffline # This corresponds to PGDATABASE in serverless.yml
    ports:
      - "5432:5432"
