restApi:
  accessLogging: true
  format: '{"resourcePath":"$context.resourcePath","requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength","errorMessage":"$context.integrationErrorMessage"}'
  executionLogging: true
  level: INFO
  fullExecutionData: true
