name: Security - OWASP ZAP Actions

on:
  workflow_dispatch:

concurrency:
  group: secuirty-develop
  cancel-in-progress: false

jobs:
  zap_scan_api:
    name: DAST (Dynamic Application Security Testing)
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: install
        run: npm install
      - name: create openapi
        run: npm run docs:bundle
      - name: Action API Scan
        uses: zaproxy/action-api-scan@v0.5.0
        env:
          ZAP_AUTH_HEADER_VALUE: testkey
          ZAP_AUTH_HEADER: x-api-key
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: build/docs/openapi.yml
          cmd_options: >
            -a
            -l PASS
            -d
            -z "-config alert.maxInstances=0
            -config view.locale=ja_JP
            -config replacer.full_list(0).description=token
            -config replacer.full_list(0).enabled=true
            -config replacer.full_list(0).matchtype=REQ_HEADER
            -config replacer.full_list(0).matchstr=x-api-key
            -config replacer.full_list(0).regex=false
            -config replacer.full_list(0).replacement=testkey"
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: YYYYMMDDHHmmss
          utcOffset: "+09:00"
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: zap_report-${{ steps.current-time.outputs.formattedTime }}
          path: |
            report_json.json
            report_md.md
            report_html.html
